apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: hashicups
spec:
  parentRefs:
  - name: api-gateway
  rules:
  - backendRefs:
    - kind: Service
      name: nginx
      port: 80